In [5]:
# Q.1 Convert a 1D array to a 2D array with 2 rows 
import numpy as np

a=np.array([2,3,4,7,8,5,9,10])
a
b=a.reshape(2,4) 
b

array([[ 2,  3,  4,  7],
       [ 8,  5,  9, 10]])

In [16]:
# Q.2 Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8]) 
ans=np.intersect1d(a,b)
ans

array([2, 4])

In [25]:
# Q.3 Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27]) 
a
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [43]:
# Q.4 Limit the number of items printed in python NumPy array a to a maximum of 6 elements.

a=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]) 

print(np.clip(a, 0, 14))


[ 0  1  2 ... 12 13 14]
