In [1]:
import pandas as pd
import numpy as np

In [32]:
#How to create an empty and a full numpy array.

a1=np.full((5,4),20.25)
print(a1)
print('\n')
a2=np.empty((5,7,2))
print(a2)

[[20.25 20.25 20.25 20.25]
 [20.25 20.25 20.25 20.25]
 [20.25 20.25 20.25 20.25]
 [20.25 20.25 20.25 20.25]
 [20.25 20.25 20.25 20.25]]


[[[0.00000000e+000 0.00000000e+000]
  [4.94065646e-324 6.95299164e-310]
  [3.26083326e-322 8.21904492e-312]
  [8.21904492e-312 8.21904469e-312]
  [8.21904492e-312 8.21904492e-312]
  [8.21904492e-312 8.21904474e-312]
  [8.21904472e-312 8.21904492e-312]]

 [[8.21904468e-312 8.21904471e-312]
  [8.21904492e-312 8.21904492e-312]
  [8.21904473e-312 8.21904472e-312]
  [8.21904471e-312 8.21904469e-312]
  [8.21904472e-312 8.21904492e-312]
  [8.21904467e-312 8.21904492e-312]
  [8.21904492e-312 8.21904470e-312]]

 [[8.21904492e-312 8.21904474e-312]
  [8.21904469e-312 8.21904492e-312]
  [8.21904466e-312 8.21904492e-312]
  [8.21904492e-312 8.21904545e-312]
  [8.21904545e-312 8.21904492e-312]
  [8.21904546e-312 8.21904492e-312]
  [8.21904539e-312 8.21904545e-312]]

 [[8.21904545e-312 8.21904546e-312]
  [8.21904544e-312 8.21904492e-312]
  [8.21904542e-312 8.2190454

In [21]:
#Create a numpy array filled with all zeros...?
a1=np.zeros(20)
print(a1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
#Create a numpy array filled with all ones...?
a2=np.ones(20)
a2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [64]:
# Check whether a numpy aeeay conatins a specific row.?
 
s2=np.array([[4,5,6],[1,2,3],[7,8,9]])
print(s2)
print([4,0,6] in s2.tolist())
print([7,8,9] in s2.tolist())


[[4 5 6]
 [1 2 3]
 [7 8 9]]
False
True


In [58]:
# How to remove rows in numpy array that contains non numerical values..?

array = np.array([[1, 2, 3],
                  [4, np.nan, 6],   # Row with non-numeric value 'g'
                  [np.nan, 8, 9],   # Row with non-numeric value 'm'
                  [10, 11, 12]])


array[~np.isnan(array).any(axis=1)]


array([[ 1.,  2.,  3.],
       [10., 11., 12.]])

In [72]:
# Remove single dimensional entries from the shapes of an array..?
array = np.array([[[1, 2, 3]]])

# Squeeze the array to remove single-dimensional entries
squeezed_array = np.squeeze(array)

print("Original shape:", array.shape)
print("Squeezed shape:", squeezed_array.shape)
array.ndim

Original shape: (1, 1, 3)
Squeezed shape: (3,)


3

In [77]:
# find the number of occurences of a sequence in a numpy array..?
arr = np.array([[2, 4, 9, 8],  
                   [9, 4, 2, 4], 
                   [2, 4, 2, 4], 
                   [2, 9, 4, 3]]) 
  
# Counting sequence 
occ = repr(arr).count("2, 4") 
  
# view output 
print(occ) 

4


In [92]:
# find the most frequent value in a numpy array..?
arr= np.array([4,5,6,4,6,4,4,4,7,8,9,0])
# ans=np.argmax(arr)
ans=np.bincount(arr).argmax()
ans

4

In [124]:
# combining a one and a two dimentional numpy array..?

a = np.array([[1, 2], [3, 4]])
print(a)
b = np.array([5,6])
print(b)
c=a+b
print(c)



[[1 2]
 [3 4]]
[5 6]
[[ 6  8]
 [ 8 10]]


In [110]:
# how to build an array of all combining of two numpy arrays..?

array1=np.array([1,2,3])
array2=np.array([[4,5,6],[9,9,0]])

x,y=np.meshgrid(array1,array2)

combination = np.column_stack((x.ravel(),y.ravel()))

print("array1 :")
print(array1)
print("array2 :")
print(array2)
print("combination :")
print(combination)


array1 :
[1 2 3]
array2 :
[[4 5 6]
 [9 9 0]]
combination :
[[1 4]
 [2 4]
 [3 4]
 [1 5]
 [2 5]
 [3 5]
 [1 6]
 [2 6]
 [3 6]
 [1 9]
 [2 9]
 [3 9]
 [1 9]
 [2 9]
 [3 9]
 [1 0]
 [2 0]
 [3 0]]


In [125]:
#function 1
array1=np.array([[1,2,3],[5,6,7]])
array2=np.array([[4,5,6],[9,9,0]])
ans=np.concatenate((array1,array2))
print(ans)


[[1 2 3]
 [5 6 7]
 [4 5 6]
 [9 9 0]]
